In [19]:
from src.primal_affine_scaling.big_m import BigMMethod
from src.primal_affine_scaling.algorithm import PrimalAffineScaling
from src.primal_affine_scaling.utils.compute_m import heuristic_m

import numpy as np
import scipy.io as sio

mat_file = sio.loadmat("data/mat/lp_stocfor1.mat")
mat_data = mat_file["Problem"]
bounds_data = mat_data[0, 0][5]

A = mat_data[0, 0][2]
b = mat_data[0, 0][3].reshape((A.shape[0],))
c = bounds_data[0, 0]['c'].reshape((1,-1))[0]

A_np = A.toarray()  
b_np = b
c_np = c

print("A shape:", A_np.shape)
print("b shape:", b_np.shape)
print("c shape:", c_np.shape)

x0 = np.ones(A_np.shape[1])  # This should match the number of columns in A

big_m = BigMMethod(
    A_np,
    b_np,
    c_np,
    10,
    rho=0.95
)
initial_point = big_m.find_initial_feasible_point(x0)



A shape: (117, 165)
b shape: (117,)
c shape: (165,)
Scaling flag: True
------ ITERATION: 0 ------
Objective: -94.64448300000001
Gap dual: 565.3580400149092
------ ITERATION: 1 ------
Objective: -579.003511793645
Gap dual: 651.1132526617014
------ ITERATION: 2 ------
Objective: -1255.9669527933816
Gap dual: 929.1486423817569
------ ITERATION: 3 ------
Objective: -3346.6603455069985
Gap dual: 1828.426741321641
------ ITERATION: 4 ------
Objective: -5752.407257853008
Gap dual: 2673.9869911733676
------ ITERATION: 5 ------
Objective: -9752.174773006765
Gap dual: 2439.8059719158346
------ ITERATION: 6 ------
Objective: -17143.39817232025
Gap dual: 3532.2434776382834
------ ITERATION: 7 ------
Objective: -23281.16518613087
Gap dual: 2208.517304566136
------ ITERATION: 8 ------
Objective: -24629.18225582916
Gap dual: 904.6806180478452
------ ITERATION: 9 ------
Objective: -25204.176763461997
Gap dual: 275.8806613767847
------ ITERATION: 10 ------
Objective: -25446.263940673307
Gap dual: 23.24

In [20]:
initial_point

array([1.40399994e+00, 2.00399992e+00, 9.76799982e+00, 1.63849987e+01,
       2.81499514e+00, 4.14992204e+01, 1.17177402e-01, 1.31613750e+00,
       1.87858933e+00, 9.15671758e+00, 1.53596222e+01, 2.30948273e+01,
       2.87123195e-05, 1.25434202e+03, 2.11780185e-01, 1.09844396e-01,
       1.23377335e+00, 1.76102666e+00, 8.58368937e+00, 1.94463837e+01,
       1.90484977e-05, 1.12890783e+03, 2.20935153e+01, 1.98526809e-01,
       1.02969967e-01, 1.15656298e+00, 1.65081937e+00, 1.13345283e+01,
       1.65753710e-05, 1.01601705e+03, 2.04051483e+01, 2.07109027e+01,
       7.41219905e-07, 4.21094012e-07, 3.67242396e-07, 3.18181206e-07,
       1.83818637e-05, 9.14415469e+02, 1.88856152e+01, 1.91281926e+01,
       2.34853669e+00, 3.14465057e-07, 1.00993252e-07, 4.84847806e-07,
       2.96202733e-05, 8.22973820e+02, 1.75180373e+01, 1.77037533e+01,
       5.36150201e+00, 1.54527507e-07, 1.44762725e-07, 1.25153983e-07,
       2.68976749e-05, 7.40676461e+02, 5.82030070e-08, 8.49915862e-08,
      

In [2]:
from scipy.sparse import diags, hstack, csc_matrix, eye
import numpy as np

from src.primal_affine_scaling.scaling import PrimalAffineScaling

c = np.array([-3, -2, 0, 0, 0])  # Objective function coefficients
A = np.array([[4, -2, 1, 0, 0], [3, 4, 0, -1, 0], [1, 1, 0, 0, 1]])  # Constraint matrix
b = np.array([5, 1, 2])  # Constraint vector
x0 = np.array([0.5, 0.5, 4.0, 5.0 / 2.0, 1.0])  # Initial feasible point

solver = PrimalAffineScaling(c, A_example_sparse, b, x0)
result = solver.solve()

print("Result:", result)

ModuleNotFoundError: No module named 'src.primal_affine_scaling.scaling'

In [ ]:
import scipy.io as sio
import numpy as np

mat_file = sio.loadmat("data/mat/lpi_bgprtr.mat")
mat_data = mat_file["Problem"]
bounds_data = mat_data[0, 0][5]

A = mat_data[0, 0][2]
b = mat_data[0, 0][3]  
c = bounds_data[0, 0]['c']

A_np = A.toarray()  
b_np = b
c_np = c

print("A shape:", A_np.shape)
print("b shape:", b_np.shape)
print("c shape:", c_np.shape)

x0 = np.ones(A_np.shape[1])  # This should match the number of columns in A

big_m = BigMMethod(
    A_np,
    b_np,
    c_np,
    heuristic_m(c_np),
)
initial_point = big_m.find_initial_feasible_point(x0)

solver = PrimalAffineScaling(
    c_np,
    A_np,
    b_np,
    initial_point,
)
result = solver.solve()


A shape: (20, 40)
b shape: (20, 1)
c shape: (40, 1)
Scaling flag: True
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 41 is different from 60)

In [3]:
c = np.array([+3, +2, 0, 0])  # Objective function coefficients
A = np.array(
    [
        [2, 1, -1, 0],
        [3, 4, 0, 1],
    ]
)  # Constraint matrix
b = np.array([2, 12])  # Constraint vector
x0 = np.array([0.5, 0.5, 4.0, 5.0 / 2.0])  # Initial feasible point

solver = PrimalAffineScaling(c, A, b, x0)
result = solver.solve()

print("Result:", result)

Scaling flag: True
[0.5 0.5 4.  2.5]
------ ITERATION: 0 ------
Objective: 2.5
Gap dual: 1.5525373134328362
[0.025      0.34209317 2.89209317 4.55662732]
------ ITERATION: 1 ------
Objective: 0.759186341308826
Gap dual: 0.21493987072535692
[0.02229076 0.01710466 2.56168618 5.86470909]
------ ITERATION: 2 ------
Objective: 0.10108159746067195
Gap dual: 0.09761989887130487
[1.11453801e-03 8.79296343e-03 2.51102204e+00 5.96148453e+00]
------ ITERATION: 3 ------
Objective: 0.020929540875480906
Gap dual: 0.02066551635240101
[9.13223441e-04 4.39648171e-04 2.50226610e+00 5.99550174e+00]
------ ITERATION: 4 ------
Objective: 0.0036189666667292677
Gap dual: 0.003614222949764007
[4.56611721e-05 3.05598489e-04 2.50039692e+00 5.99864062e+00]
------ ITERATION: 5 ------
Objective: 0.0007481804933333981
Gap dual: 0.0007478613289166309
[3.59391237e-05 1.52799244e-05 2.50008716e+00 5.99983106e+00]
------ ITERATION: 6 ------
Objective: 0.00013837721980814984
Gap dual: 0.0001383700929372091
[1.79695618e-